services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: barbershop_db
      POSTGRES_USER: eito
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: